#!/usr/bin/env bash

# Configure user-specific values for dotfiles
# Run this before install.sh to set up your personal config

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG_FILE="$SCRIPT_DIR/.user.conf"

echo "Dotfiles Configuration"
echo "======================"
echo ""

# Load existing config if present
if [ -f "$CONFIG_FILE" ]; then
    source "$CONFIG_FILE"
    echo "Found existing configuration. Press Enter to keep current values."
    echo ""
fi

# Prompt for values with defaults from existing config or git
read -p "Git name [${GIT_NAME:-$(git config --global user.name 2>/dev/null || echo '')}]: " input_name
GIT_NAME="${input_name:-${GIT_NAME:-$(git config --global user.name 2>/dev/null)}}"

read -p "Git email [${GIT_EMAIL:-$(git config --global user.email 2>/dev/null || echo '')}]: " input_email
GIT_EMAIL="${input_email:-${GIT_EMAIL:-$(git config --global user.email 2>/dev/null)}}"

read -p "GitHub username [${GH_USERNAME:-}]: " input_gh_user
GH_USERNAME="${input_gh_user:-${GH_USERNAME}}"

# Save configuration
cat > "$CONFIG_FILE" <<EOF
# User-specific dotfiles configuration
# Generated by configure.sh - do not commit this file

GIT_NAME="$GIT_NAME"
GIT_EMAIL="$GIT_EMAIL"
GH_USERNAME="$GH_USERNAME"
EOF

echo ""
echo "Configuration saved to .user.conf"
echo ""

# Generate actual config files from templates
echo "Generating config files from templates..."

# Function to replace placeholders in template
generate_from_template() {
    local template="$1"
    local output="$2"

    if [ ! -f "$template" ]; then
        echo "  Warning: Template not found: $template"
        return
    fi

    sed -e "s|{{GIT_NAME}}|$GIT_NAME|g" \
        -e "s|{{GIT_EMAIL}}|$GIT_EMAIL|g" \
        -e "s|{{GH_USERNAME}}|$GH_USERNAME|g" \
        "$template" > "$output"

    echo "  Generated: $output"
}

# Generate git config
generate_from_template "$SCRIPT_DIR/git/.gitconfig.template" "$SCRIPT_DIR/git/.gitconfig"

# Generate .envrc (only if GitHub username is set)
if [ -n "$GH_USERNAME" ]; then
    generate_from_template "$SCRIPT_DIR/.envrc.template" "$SCRIPT_DIR/.envrc"
else
    echo "  Skipping .envrc (no GitHub username provided)"
    # Remove .envrc if it exists to avoid stale config
    rm -f "$SCRIPT_DIR/.envrc"
fi

echo ""
echo "Done! You can now run ./install.sh"
